### PR TITLE
Feat/#35 implement fe login

### LINKED ISSUE #35: feat: implement FE login/signup

### PR DESCRIPTION
**Pull request by marianoheller**
closes #35 

Created signup, login views with almost all the functionality (with *local* logout).

As dependencies added formik for forms(pretty cool library), yup for validation and roboto font.
Added 2 links on the Landing page (login and signup) just to easy access to those views.
To logout -> access /logout.

Added some random style and views lack style, but thats for another issue.

Going to create another issue on the same epic to solve a minor thing with this PR (gotta figure out how to inject a state prop into the formik form to show "request in progress", "loading" or something)

### CODE REVIEW

**Comment by marianoheller** [comment]
Oh and I had to do a minor modification to the client's linter config.
Removed `"components": [ "Link" ],` cuz it wouldn't let me use router's Links.

**Review by ziggysauce — APPROVED** [review]
Setup looks good. Styling for components looks fine for now too.

**Comment by ziggysauce** [comment]
For others checking out this PR, make sure you `npm install` while inside the `client` directory!

**Comment by mvoltairec** [comment]
closes #35

**Pull request merged**
